name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - run: cargo build --verbose
      - run: sudo modprobe nbd
      - run: cargo test --verbose
      - run: cargo clippy --tests --no-deps -- -D clippy::all
